import type { Phrase } from "@/lib/domain/types";

// Taxi Swedish phrase bank (spec §9). Functional, on-the-job Swedish with
// French translation, a pronunciation hint for French speakers, and context.

export const PHRASES: Phrase[] = [
  {
    id: "ph_greet",
    category: "Hälsning",
    swedishText: "Hej! Vart vill du åka?",
    frenchTranslation: "Bonjour ! Où voulez-vous aller ?",
    pronunciationHint: "hey – vart vill dou ôka",
    contextFr: "Saluer le passager et demander la destination.",
    politeVariant: "God dag! Vart skulle du vilja åka?",
    difficultyLevel: 1,
  },
  {
    id: "ph_confirm_dest",
    category: "Destination",
    swedishText: "Ska vi åka till Centralstationen?",
    frenchTranslation: "On va à la gare centrale ?",
    pronunciationHint: "ska vi ôka till sentral-stachounen",
    contextFr: "Confirmer la destination avant de partir.",
    difficultyLevel: 1,
  },
  {
    id: "ph_route_pref",
    category: "Vägval",
    swedishText: "Vill du ta snabbaste eller billigaste vägen?",
    frenchTranslation: "Préférez-vous le chemin le plus rapide ou le moins cher ?",
    pronunciationHint: "vill dou ta snab-aste eller bil-igaste veggen",
    contextFr: "Proposer un choix d'itinéraire.",
    difficultyLevel: 2,
  },
  {
    id: "ph_payment",
    category: "Betalning",
    swedishText: "Hur vill du betala, kort eller kontant?",
    frenchTranslation: "Comment voulez-vous payer, carte ou espèces ?",
    pronunciationHint: "hour vill dou betala, kort eller kontant",
    contextFr: "Demander le moyen de paiement.",
    difficultyLevel: 1,
  },
  {
    id: "ph_receipt",
    category: "Kvitto",
    swedishText: "Vill du ha ett kvitto?",
    frenchTranslation: "Voulez-vous un reçu ?",
    pronunciationHint: "vill dou ha ett kvitto",
    contextFr: "Proposer un reçu en fin de course.",
    difficultyLevel: 1,
  },
  {
    id: "ph_luggage",
    category: "Bagage",
    swedishText: "Får jag hjälpa dig med väskorna?",
    frenchTranslation: "Puis-je vous aider avec vos valises ?",
    pronunciationHint: "fôr yag yelpa dey med vesk-orna",
    contextFr: "Proposer de l'aide pour les bagages.",
    difficultyLevel: 2,
  },
  {
    id: "ph_seatbelt",
    category: "Säkerhet",
    swedishText: "Kom ihåg att ta på bältet, tack.",
    frenchTranslation: "Pensez à mettre votre ceinture, s'il vous plaît.",
    pronunciationHint: "kom i-hôg att ta pô beltet, tack",
    contextFr: "Rappeler la ceinture de sécurité.",
    difficultyLevel: 1,
  },
  {
    id: "ph_delay",
    category: "Förseningar",
    swedishText: "Det är mycket trafik, det kan ta lite längre tid.",
    frenchTranslation: "Il y a beaucoup de circulation, cela peut prendre un peu plus de temps.",
    pronunciationHint: "de er mycke trafik, de kan ta lite lengre tid",
    contextFr: "Prévenir d'un retard dû au trafic.",
    difficultyLevel: 2,
  },
  {
    id: "ph_accessibility",
    category: "Tillgänglighet",
    swedishText: "Hur vill du att jag hjälper dig?",
    frenchTranslation: "Comment souhaitez-vous que je vous aide ?",
    pronunciationHint: "hour vill dou att yag yelper dey",
    contextFr: "Demander à un passager comment l'assister (accessibilité).",
    difficultyLevel: 2,
  },
  {
    id: "ph_arrived",
    category: "Ankomst",
    swedishText: "Nu är vi framme. Det blir 245 kronor.",
    frenchTranslation: "Nous sommes arrivés. Cela fait 245 couronnes.",
    pronunciationHint: "nou er vi framme. de blir tvô-hundra-förti-fem krou-nor",
    contextFr: "Annoncer l'arrivée et le prix.",
    difficultyLevel: 2,
  },
];
